apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: zookeeper
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/mortent/kpt-demos
    branch: main
    dir: "gcloud-ui/packages/zookeeper"
    auth: none
